### ISSUE TITLE
dbContextoptions action needs an overload to also pass in the serviceProvider

### ISSUE THREAD

**Issue by hades200082** [pierodetomi/efcore-identity-cosmos#10]
On `services.AddDbContext<MyDbContext>()` I can call it like this:

```csharp
services.AddDbContext<MyDbContext>((serviceProvider, options) =>
        {
            var cosmosOptions = serviceProvider.GetRequiredService<IOptions<CosmosOptions>>().Value;
            var httpClientFactory = serviceProvider.GetRequiredService<IHttpClientFactory>();
            options.UseCosmos(
                cosmosOptions.AccountEndpoint!,
                cosmosOptions.AccountKey!,
                databaseName: cosmosOptions.DatabaseId!,
                builder =>
                {
                    if (environment.IsDevelopment())
                        builder.ConnectionMode(ConnectionMode.Gateway);
                    
                    builder.HttpClientFactory(() => httpClientFactory.CreateClient(nameof(CosmosDbContext)));
                }
            );
            options.EnableSensitiveDataLogging();
        });
```

This allows me to do some important stuff that is needed if I want to use the Cosmos DB Emulator in docker when working locally.

The current implementation of `services.AddCosmosIdentity` doesn't seem to allow for passing in the serviceProvider to the dbContextOptions.

**Comment by pierodetomi** [comment]
Hi @hades200082, I'm sorry, but unfortunately, I'm not actively maintaining this repository anymore. Consequently, I'm not up to date with these kinds of details.
I know that someone forked my repository some time ago and is actively maintaining it. They've even upgraded the .NET version and made other improvements. Perhaps you can look after that fork.
