### ISSUE TITLE
Option to have all records in one container with partitions

### ISSUE THREAD

**Issue by hades200082** [pierodetomi/efcore-identity-cosmos#11]
With cosmos db a container is not the same as a table in SQL. Its designed to work like a document db where all records of all types can go in one container and uses partition keys to point to storage locations for the data.

Is there an option to use this package in that way?

**Comment by hades200082** [comment]
Dead project?

**Comment by pierodetomi** [comment]
Hi,

Essentially, yes. It’s clearly stated in the repository description: “Not actively maintained.” ☺️

This project started mainly for study purposes. Unfortunately, I don’t have the time to update it.

Thank you for your understanding.
