### ISSUE TITLE
.Net 5 no longer supported - Refactor for 6 LTS?

### ISSUE THREAD

**Issue by toiyabe** [pierodetomi/efcore-identity-cosmos#9]
Hello!

.Net 5 fell out of support in [May 2022](https://devblogs.microsoft.com/dotnet/dotnet-5-end-of-support-update/), would anyone mind if I refactor for 6 LTS?

Also, follow-up questions:

* IdentityServer4 [is being depreciated](https://modlogix.com/blog/identityserver4-alternatives-best-options-and-the-near-future-of-identityserver/) for a new product called Duende.IdentityServer, which requires a license for commercial use. With this knowledge, should this library drop support for Duende.IdentityServer (i.e PersistedGrantEntityTypeConfiguration in the class ModelBuilderExtensions)?
* Last question, do unit tests exist for this project?

Thanks,

-Eric

**Comment by toiyabe** [comment]
Hello again,

I had an immediate need to refactor this for 6, I decided to create a new repo based on your work Piero. You are a terrific developer. I love your work!

Here is that repo:

https://github.com/CosmosSoftware/AspNetCore.Identity.CosmosDb

Thank you for your hard work!

-Eric

**Comment by pierodetomi** [comment]
Hi Eric!

Thank you very much for your kind words, and I apologize for the late reply but this has been (and still is) a very busy period and unfortunately I didn't have the chance to reply in time.

Please feel free to merge back your work to this repo if you wish.

Cheers,
Piero
